Zadania/Controllers/CompanyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NetStarCore5.Helpers;
using Newtonsoft.Json;
using Zadania.Data;
using Zadania.Helpers.SRTProcessor;
using Zadania.Models;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Zadania.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ILogger<CompanyController> _logger;
        private readonly IHttpClientFactory _clientFactory;
        private IMapper _mapper;
        private readonly DatabaseContext _context;
        private readonly SubtitleProcessor _subtitleProcessor;
        IWebHostEnvironment _hostingEnvironment;
        public CompanyController(
            ILogger<CompanyController> logger,
            IHttpClientFactory clientFactory,
            IMapper mapper,
            DatabaseContext context,
             IWebHostEnvironment hostingEnvironment
            )
        {
            _logger = logger;
            _clientFactory = clientFactory;
            _mapper = mapper;
            _context = context;
            _subtitleProcessor = new SubtitleProcessor();
            _hostingEnvironment = hostingEnvironment;
        }
        public async  Task<IActionResult> Index()
        {
            //var companysDB = await _context.Subjects.Include(x => x.representatives).Include(x => x.authorizedClerks).ToListAsync();

         
            

            return View();
        }

        public async Task<IActionResult> IndexReact()
        {
            
            var entityPersonWspolnik = _context.EntityPersonWspolniks.FirstOrDefault(x => x.EntityPersonWspolnikId == 2);
            if (entityPersonWspolnik != null)
            {

                _context.EntityPersonWspolniks.Remove(entityPersonWspolnik);
                _context.SaveChanges();
            }
            var entityPersonProkurent = _context.EntityPersonProkurents.FirstOrDefault(x => x.EntityPersonProkurentId == 2);
            if (entityPersonProkurent != null)
            {

                _context.EntityPersonProkurents.Remove(entityPersonProkurent);
                _context.SaveChanges();
            }
            var representatives = _context.Representatives.FirstOrDefault(x => x.RepresentativeId == 2);
            if (representatives != null)
            {

                _context.Representatives.Remove(representatives);
                _context.SaveChanges();
            }
            var company = _context.Subjects.FirstOrDefault(x => x.SubjectId == 2);
            if (company != null)
            {
               
                _context.Subjects.Remove(company);
                _context.SaveChanges();
            }
            
            return View();
        }

        public async Task<IActionResult> LoadCompanyDataAjax(string nip = "")
        {
            Subject companyDB = null;

            
            if (!string.IsNullOrEmpty(nip))
            {
                companyDB = await _context.Subjects.Where(x => x.nip == nip).Include(x => x.partners).Include(x => x.representatives).Include(x => x.authorizedClerks).FirstOrDefaultAsync();
                if (companyDB == null)
                {
                    var client = _clientFactory.CreateClient();

                    //var client = new HttpClient();
                    client.BaseAddress = new Uri("https://wl-api.mf.gov.pl");
                    client.DefaultRequestHeaders.Accept.Clear();

                    HttpRequestMessage request = null;
                    HttpResponseMessage response = null;
                    var dateCyrrent = DateTime.Now.ToString("yyyy-MM-dd");


                    response = await client.GetAsync($"/api/search/nip/{nip}?date={dateCyrrent}");




                    var sessionId = "";
                    if (response.IsSuccessStatusCode)
                    {
                        //sessionId = await responseSessionId.Content.ReadAsStringAsync();


                        var responseContent = await response.Content.ReadAsStringAsync();
                        RootVM companyData = JsonConvert.DeserializeObject<RootVM>(responseContent);

                        companyDB = new Subject();
                        companyDB.krs = companyData.result.subject.krs != null ? companyData.result.subject.krs : "";
                        companyDB.nip = companyData.result.subject.nip != null ? companyData.result.subject.nip : "";

                        if (companyData.result.subject.partners != null && companyData.result.subject.partners.Count() > 0)
                        {
                            EntityPersonWspolnik entityPersonWspolnik = new EntityPersonWspolnik();
                            foreach (var item in companyData.result.subject.partners)
                            {
                                entityPersonWspolnik.nip = item.nip != null ? item.nip : "";
                                entityPersonWspolnik.firstName = item.firstName != null ? item.firstName : "";
                                entityPersonWspolnik.lastName = item.lastName != null ? item.lastName : "";
                                entityPersonWspolnik.companyName = item.companyName != null ? item.companyName : "";
                                entityPersonWspolnik.pesel = item.pesel != null ? item.pesel : "";

                            }
                            companyDB.partners.Add(entityPersonWspolnik);
                        }
                        companyDB.name = companyData.result.subject.name != null ? companyData.result.subject.name : "";
                        companyDB.pesel = companyData.result.subject.pesel != null ? companyData.result.subject.pesel : "";
                        companyDB.registrationDenialDate = companyData.result.subject.registrationDenialDate != null ? companyData.result.subject.registrationDenialDate : "";
                        companyDB.registrationLegalDate = companyData.result.subject.registrationLegalDate != null ? companyData.result.subject.registrationLegalDate : "";
                        companyDB.regon = companyData.result.subject.regon != null ? companyData.result.subject.regon : "";
                        companyDB.removalDate = companyData.result.subject.removalDate != null ? companyData.result.subject.removalDate : "";
                        companyDB.removalBasis = companyData.result.subject.removalBasis != null ? companyData.result.subject.removalBasis : "";

                        if (companyData.result.subject.representatives != null && companyData.result.subject.representatives.Count() > 0)
                        {
                            Representative representative = new Representative();
                            foreach (var item in companyData.result.subject.representatives)
                            {
                                representative.nip = item.nip != null ? item.nip : "";
                                representative.firstName = item.firstName != null ? item.firstName : "";
                                representative.lastName = item.lastName != null ? item.lastName : "";
                                representative.companyName = item.companyName != null ? item.companyName : "";


                            }
                            companyDB.representatives.Add(representative);
                        }
                        companyDB.residenceAddress = companyData.result.subject.residenceAddress != null ? companyData.result.subject.residenceAddress : "";
                        companyDB.statusVat = companyData.result.subject.statusVat != null ? companyData.result.subject.statusVat : "";
                        companyDB.workingAddress = companyData.result.subject.workingAddress != null ? companyData.result.subject.workingAddress : "";
                        companyDB.restorationBasis = companyData.result.subject.restorationBasis != null ? companyData.result.subject.restorationBasis : "";
                        companyDB.restorationDate = companyData.result.subject.restorationDate != null ? companyData.result.subject.restorationDate : "";
                        companyDB.registrationDenialBasis = companyData.result.subject.registrationDenialBasis != null ? companyData.result.subject.registrationDenialBasis : "";
                        companyDB.registrationDenialDate = companyData.result.subject.registrationDenialDate != null ? companyData.result.subject.registrationDenialDate : "";

                        if (companyData.result.subject.authorizedClerks != null && companyData.result.subject.authorizedClerks.Count() > 0)
                        {
                            EntityPersonProkurent entityPersonProkurent = new EntityPersonProkurent();
                            foreach (var item in companyData.result.subject.authorizedClerks)
                            {
                                entityPersonProkurent.nip = item.nip != null ? item.nip : "";
                                entityPersonProkurent.firstName = item.firstName != null ? item.firstName : "";
                                entityPersonProkurent.lastName = item.lastName != null ? item.lastName : "";
                                entityPersonProkurent.companyName = item.companyName != null ? item.companyName : "";
                                entityPersonProkurent.pesel = item.pesel != null ? item.pesel : "";

                            }
                            companyDB.authorizedClerks.Add(entityPersonProkurent);
                        }


                        //var resoult = _mapper.Map<Root>(companyData);

                        string fileName = "CompanyData.json";
                        //string fileName1 = "test.json";
                        var folderDataFileJSON = "DataFiles/Json/";
                        var dataFileJsonPatchListNotFile = Path.Combine(_hostingEnvironment.WebRootPath, folderDataFileJSON);

Zadania/Controllers/TaskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Zadania.Data;
using Zadania.Helpers.SRTProcessor;
using Zadania.Models;

namespace Zadania.Controllers
{
    public class TaskController : Controller
    {

        private readonly ILogger<TaskController> _logger;

        private readonly DatabaseContext _context;

        public TaskController(
            ILogger<TaskController> logger,
            DatabaseContext context
            )
        {
            _logger = logger;
            _context = context;

        }
        public IActionResult Index()
        {
            var tasks = _context.Tasks.ToList();
            return View(tasks);
           
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(TaskEntry taskEntry)
        {
            if (ModelState.IsValid)
            {
                
                _context.Tasks.Add(taskEntry);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(taskEntry);
        }

        [HttpPost]
        public IActionResult Stop(int id)
        {
            var taskEntry = _context.Tasks.Find(id);
            if (taskEntry != null)
            {
                
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }



    }
}

Zadania/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zadania</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Zadania.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Css", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zadania</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Pobranie danych firmy ajax (Zadanie 1)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="IndexReact">Pobranie danych firmy React (Zadanie 1) </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TextMovie" asp-action="Index">Pobranie pliku z napisami i zmiana (Zadanie 2A)</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Pomiar czasu zadania (Zadanie 2B)</a>
                        </li>
                      
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Zadania Artur Pogorzelski
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>