Zadania/Controllers/TextMovieController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Formats.Tar;
using Zadania.Data;
using Zadania.Helpers.SRTProcessor;
using Zadania.Models;

namespace Zadania.Controllers
{
    public class TextMovieController : Controller
    {
        IWebHostEnvironment _hostingEnvironment;
        private readonly ILogger<TextMovieController> _logger;
        private readonly SubtitleProcessor _subtitleProcessor;
        private readonly DatabaseContext _context;
        public TextMovieController(
            IWebHostEnvironment hostingEnvironment, 
            DatabaseContext context)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
            _subtitleProcessor = new SubtitleProcessor();
        }
        [HttpGet]
        public async  Task<IActionResult> Index()
        {
            ReturnMovieFilesVM resoult = new ReturnMovieFilesVM();
            resoult.IsFirst = true;

            var movieTexts = await _context.MovieTexts.ToListAsync();

            if (movieTexts != null && movieTexts.Count() > 0)
            {
                resoult.MovieTextsList = movieTexts;
              
            }
          
            return View(resoult);
        }

        // GET: /File/Upload
       

        // POST: /File/Upload
        [HttpPost]
        public async Task<IActionResult> Index(IFormFile file)
        {
            var isOk = false;

            string filePathSaveDB = string.Empty;
            string filePathSaveOutput1DB = string.Empty;
            string filePathSaveOutput2DB = string.Empty;
            string fileName = string.Empty;

            ReturnMovieFilesVM resoult = new ReturnMovieFilesVM();
            if (file != null && file.Length > 0)
            {
                try
                {
                    fileName = file.FileName;


                    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "fileOrigingl", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }



                    var fileNameOutput1 = "Output1-" + fileName;
                    var fileNameOutput2 = "Output2-" + fileName;
                    string filePathOutput1 = Path.Combine(_hostingEnvironment.WebRootPath, "files", fileNameOutput1);
                    string filePathOutput2 = Path.Combine(_hostingEnvironment.WebRootPath, "files", fileNameOutput2);

                    filePathSaveDB = Path.Combine("fileOrigingl", fileName);
                    filePathSaveOutput1DB = Path.Combine("files", fileNameOutput1);
                    filePathSaveOutput2DB = Path.Combine("files", fileNameOutput2);

                    TimeSpan timeShift = new TimeSpan(00, 00, 00, 05, 880); // 5 sekund i 880 milisekund
                                                                            // outputFilePath = filePathOutput;
                                                                            // TimeSpan timeShift = TimeSpan.FromSeconds(5.880);


                    _subtitleProcessor.ProcessSubtitles(filePath, filePathOutput1, filePathOutput2, timeShift);

                    MovieText movieText = new MovieText();
                    movieText.Name = fileName;
                    movieText.TextOriginalUrl = filePathSaveDB;
                    movieText.TextUpdate1Url = filePathSaveOutput1DB;
                    movieText.TextUpdate2Url = filePathSaveOutput2DB;
                    movieText.DateCreated = DateTime.Now;
                    _context.MovieTexts.Add(movieText);
                    await _context.SaveChangesAsync();

                    ViewBag.Message = "Plik został wgrany i podzielony i wszystkie pliki zostały zapisane na nysku i w bazie danych.";
                    isOk = true;

                    resoult.Message = "Plik został wgrany i podzielony i wszystkie pliki zostały zapisane na nysku i w bazie danych.";
                    resoult.IsOk = isOk;
                    var movieTexts = await _context.MovieTexts.ToListAsync();

                    if (movieTexts != null && movieTexts.Count() > 0)
                    {
                        resoult.MovieTextsList = movieTexts;
                        resoult.MovieText = movieText;
                    }
                }
                catch (Exception ex)
                {
                    isOk = false;
                    ViewBag.Message = $"Wystąpił błąd: {ex.Message}";
                    resoult.Message = $"Wystąpił błąd: {ex.Message}";
                    resoult.IsOk = isOk;
                    resoult.IsError = true;
                }
            }
            else
            {
                try 
                {
                    TimeSpan timeShift = new TimeSpan(00, 00, 00, 05, 880); // 5 sekund i 880 milisekund
                    var fileNameDysk = "napisy-do-filmu.srt";
                    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, "fileOrigingl", fileNameDysk);

                    var fileNameOutput1 = "Output1-" + fileNameDysk;
                    var fileNameOutput2 = "Output2-" + fileNameDysk;
                    string filePathOutput1 = Path.Combine(_hostingEnvironment.WebRootPath, "files", fileNameOutput1);
                    string filePathOutput2 = Path.Combine(_hostingEnvironment.WebRootPath, "files", fileNameOutput2);


                    filePathSaveDB = Path.Combine("fileOrygingl", fileNameDysk);
                    filePathSaveOutput1DB = Path.Combine("files", fileNameOutput1);
                    filePathSaveOutput2DB = Path.Combine("files", fileNameOutput2);


                    _subtitleProcessor.ProcessSubtitles(filePath, filePathOutput1, filePathOutput2, timeShift);
                    ViewBag.Message = "Plik został pobrany z dysku podzielony i wszystkie pliki zostały zapisane na nysku i w bazie danych.";

                    MovieText movieText = new MovieText();
                    movieText.Name = fileName;
                    movieText.TextOriginalUrl = filePathSaveDB;
                    movieText.TextUpdate1Url = filePathSaveOutput1DB;
                    movieText.TextUpdate2Url = filePathSaveOutput2DB;
                    movieText.DateCreated = DateTime.Now;
                    _context.MovieTexts.Add(movieText);
                    await _context.SaveChangesAsync();


                    isOk = true;
                    resoult.Message = "Plik został pobrany z dysku podzielony i wszystkie pliki zostały zapisane na nysku i w bazie danych.";
                    resoult.IsOk = isOk;

                    var movieTexts = await _context.MovieTexts.ToListAsync();

                    if (movieTexts != null && movieTexts.Count() > 0) 
                    {
                        resoult.MovieTextsList = movieTexts;
                        resoult.MovieText = movieText;
                    }


                }
                catch(Exception ex) 
                {
                    isOk = false;
                    ViewBag.Message = $"Wystąpił błąd: {ex.Message}";
                    resoult.Message = $"Wystąpił błąd: {ex.Message}";
                    resoult.IsOk = isOk;
                    resoult.IsError = true;
                }
                

                
            }

            return View(resoult);


        }


        public async Task<IActionResult> GetFile(int id, int which) 
        {
            var movieFile = await _context.MovieTexts.Where(x => x.Id == id).FirstOrDefaultAsync();

            if (movieFile != null)
            {
                if (which == 1)
                {
                    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, movieFile.TextOriginalUrl);
                    if (System.IO.File.Exists(filePath))
                    {
                        string fileContent = System.IO.File.ReadAllText(filePath);
                        return Content(fileContent, "text/plain");
                    }
                    else
                    {
                        // return NotFound();
                        return RedirectToAction("Index");
                    }
                }
               else if (which == 2)
                {
                    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, movieFile.TextUpdate1Url);
                    if (System.IO.File.Exists(filePath))
                    {
                        string fileContent = System.IO.File.ReadAllText(filePath);
                        return Content(fileContent, "text/plain");
                    }
                    else
                    {
                        // return NotFound();
                        return RedirectToAction("Index");
                    }
                }
               else if (which == 3)
                {
                    string filePath = Path.Combine(_hostingEnvironment.WebRootPath, movieFile.TextUpdate2Url);
                    if (System.IO.File.Exists(filePath))
                    {
                        string fileContent = System.IO.File.ReadAllText(filePath);
                        return Content(fileContent, "text/plain");
                    }
                    else
                    {
                        // return NotFound();
                        return RedirectToAction("Index");
                    }
                }

                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }


        }


    }
}

Zadania/Views/TextMovie/Index.cshtml
@using Zadania.Models
@model ReturnMovieFilesVM
@{
    Layout = "_Layout";

    ReturnMovieFilesVM returnMovieFilesVM = null;
    List<MovieText> movieTextsList = new List<MovieText>();
    MovieText movieText = new MovieText();
    if (Model != null)
    {
        returnMovieFilesVM = Model;
        if (Model.MovieTextsList != null && Model.MovieTextsList.Count() > 0)
        {

            movieTextsList = Model.MovieTextsList;
        }
        if (Model.MovieText != null)
        {

            movieText = Model.MovieText;
        }
    }

}

<h1>Pobieranie pliku</h1>
<br>
<p>
    opis: pobieramy plik z dysku i klikamy wyślij pliki wynikowe zapisuję się w katalogu głównym witryny wwwroot/files plik oryginalny zapisyje się w katalogu wwwroot/fileOrigingl każdorazowo zapisujemy operację do bazy danych i wyświetlamy listę wszystkich pobranych plików, które możemy podglądnąć zgodnie z opisem w tabeli. jeżeli nie wybierzemy pliku a klikniemy wyślij to program pobierze plik oryginalny z dysku (plik podany przez Państwa do zadania)   
</p>
<br>
@if (returnMovieFilesVM != null && returnMovieFilesVM.IsFirst)
{
    <form method="post" enctype="multipart/form-data">
       @* <div>
            <label for="file">Wybierz plik:</label>
            <input type="file" id="file" name="file" />
        </div>
        <button type="submit">Wyślij</button>*@

        <div class="input-group">
            <input type="file" class="form-control" id="file" name="file" aria-describedby="inputGroupFileAddon04" aria-label="Wybierz plik">
            <button class="btn btn-outline-secondary" type="submit" >Wyślij</button>
        </div>

    </form>

    <h2>Lista zmienionych plików z Bazy Danych</h2>
    <table class="table table-bordered">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Data</th>
            <th scope="col">
                Url pliku orginalnego
            </th>
            <th scope="col">
                Url  1 pliku wynikowego
            </th>
            <th scope="col">
                Url  2 pliku wynikowego
            </th>
        </tr>
        @foreach (var item in movieTextsList)
        {
            <tr>
                <th scope="row">
                    @item.Id
                </th>
                <td>
                    @item.DateCreated
                </td>
                <td>
                    @item.TextOriginalUrl<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 1 })" target="_blank">Podgląd pliky</a>
                </td>
                <td>
                    @item.TextUpdate1Url<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 2 })" target="_blank">Podgląd pliky</a>
                </td>
                <td>
                    @item.TextUpdate2Url<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 3 })" target="_blank">Podgląd pliky</a>
                </td>
            </tr>
        }
    </table>
}else
{
        <h2>Lista zmienionych plików z Bazy Danych</h2>
    <table class="table table-bordered">
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Data</th>
            <th scope="col">
                    Url pliku orginalnego
                </th>
            <th scope="col">
                    Url  1 pliku wynikowego
                </th>
            <th scope="col">
                    Url  2 pliku wynikowego
                </th>
            </tr>
        @foreach (var item in movieTextsList)
        {
            <tr>
                <th scope="row">
                    @item.Id
                </th>
                <td>
                    @item.DateCreated
                </td>
                <td>
                    @item.TextOriginalUrl<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 1 })" target="_blank">Podgląd pliky</a>
                </td>
                <td>
                    @item.TextUpdate1Url<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 2 })" target="_blank">Podgląd pliky</a>
                </td>
                <td>
                    @item.TextUpdate2Url<br><br>
                    <a href="@Url.Action("GetFile", "TextMovie", new { id = @item.Id, which = 3 })" target="_blank">Podgląd pliky</a>
                </td>
            </tr>
        }
        </table>
}


@if (!string.IsNullOrEmpty(ViewBag.Message))
{
    <div>
        <p>@ViewBag.Message</p>
    </div>
}